# Pipeline control rules
# Only use branch and tag pipelines for simplicity, not merge_request_event
workflow:
  rules:
    # Tag: rebuild docker as a tagged
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG: "$CI_COMMIT_TAG"
        BUILD_IMAGE: 1
    # Main branch: rebuild docker as a 'latest'
    # (can't use a variable inside 'if' for the branch name)
    - if: '$CI_COMMIT_BRANCH == "esp-linux-1.28.x-dev"'
      variables:
        BUILD_IMAGE: 1
    # Feature branch, docker image has changed: an SHA-tagged image
    # (can't use a variable inside 'compare_to' for the branch name)
    - if: $CI_COMMIT_BRANCH
      changes:
        compare_to: 'refs/heads/esp-linux-1.28.x-dev'
        paths:
          - .gitlab/docker/**/*
      variables:
        IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
        BUILD_IMAGE: 1
    # Feature branch, docker image has not changed: don't rebuild docker, use 'latest'
    - if: $CI_COMMIT_BRANCH

stages:
  - images
  - generate_version
  - build
  - internal_deploy
  - docker

include:
  - { file: /include/build_image.yml, project: ci/gitlab-templates, ref: v1 }

variables:
  BUILD_IMAGE: 0
  IMAGE_TAG: "latest"
  IMAGE_REGISTRY: "${CI_REGISTRY_IMAGE}/esp-linux-1.28.x-dev"

  # GIT_STRATEGY - use option from "CI / CD Settings" - "General pipelines"
  GIT_SUBMODULE_STRATEGY: normal

  # show artifact downloading progress
  TRANSFER_METER_FREQUENCY: 5s

  ARCHIVE_TOOL: "tar -cJvf" # 'v' we need to check the contents of the archive by log
  UNARCHIVE_TOOL: "tar -xf"
  ARCHIVE_EXT: "tar.xz"

  GIT_SERVER: "${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}"

  CONF_TARGET: "riscv64-esp-linux-gnu"

.use_ci_tools: &use_ci_tools |
  curl -sSL ${CIT_LOADER_URL} -o cit_loader.sh && sh cit_loader.sh
  source citools/import_functions

# ESPCI_HOMEBREW_PREFIX is set up in runner's config.toml
.check_and_setup_homebrew: &check_and_setup_homebrew |
  if [[ "$OSTYPE" == "darwin"* ]]; then
    eval "$(${ESPCI_HOMEBREW_PREFIX}/bin/brew shellenv)"
  fi

default:
  image: ${IMAGE_REGISTRY}-default:${IMAGE_TAG}
  before_script:
    - *use_ci_tools
    - *check_and_setup_homebrew

# Configure crosstool-NG
.build_ctng: &build_ctng |
  ./bootstrap
  ./configure --enable-local
  make
  ./ct-ng ${CONF_TARGET}

# ct-ng options common for all platforms
.configure_common: &configure_common |
  echo "# CT_LOG_PROGRESS_BAR is not set" >> .config
  echo "# CT_PREFIX_DIR_RO is not set" >> .config
  echo "CT_LOG_EXTRA=y" >> .config
  echo "CT_LOG_LEVEL_MAX=\"EXTRA\"" >> .config
  echo "CT_LOG_TO_FILE=y" >> .config
  echo "# CT_LOG_FILE_COMPRESS is not set" >> .config
  echo "CT_KERNEL_LINUX_INSTALL_CHECK=y" >> .config
  echo "CT_USE_MIRROR=y" >> .config
  echo "CT_FORCE_MIRROR=y" >> .config
  echo "CT_MIRROR_BASE_URL=\"${MIRROR_BASE}\"" >> .config
  echo "CT_GCC_DEVEL_URL=\"${GIT_SERVER}/idf/gcc.git\"" >> .config
  echo "CT_GLIBC_DEVEL_URL=\"${GIT_SERVER}/idf/glibc.git\"" >> .config
  echo "CT_BINUTILS_DEVEL_URL=\"${GIT_SERVER}/idf/binutils-gdb.git\"" >> .config
  echo "CT_GDB_DEVEL_URL=\"${GIT_SERVER}/idf/binutils-gdb.git\"" >> .config
  echo "# CT_DEBUG_GDB is not set" >> .config

# TODO: GCC-432, fix GDB build, use GCC 8+ version (C++17) on host

# Configuration specific to Docker
.configure_docker: &configure_docker |
  echo "CT_ALLOW_BUILD_AS_ROOT=y" >> .config
  echo "CT_ALLOW_BUILD_AS_ROOT_SURE=y" >> .config
  echo "CT_CONNECT_TIMEOUT=30" >> .config

# If PIE is enabled by default in build GCC, add a flag to disable it
# For example, it appears on Ubuntu 17.04 or Debian 9
.configure_linux_no_pie: &configure_linux_no_pie |
  gcc -v |& grep -- --enable-default-pie > /dev/null && echo "CT_EXTRA_LDFLAGS_FOR_HOST=\"-no-pie\"" >> .config

# Configuration specific to crossbuilds
.configure_crossbuild: &configure_crossbuild |
  echo "CT_CANADIAN=y" >> .config
  echo "CT_BUILD=\"${CONF_BUILD}\"" >> .config
  echo "CT_BUILD_PREFIX=\"${CONF_BUILD}-\"" >> .config
  echo "CT_BUILD_SUFFIX=\"\"" >> .config
  echo "CT_HOST=\"${CONF_HOST}\"" >> .config
  echo "CT_HOST_PREFIX=\"${CONF_HOST}-\"" >> .config
  echo "CT_HOST_SUFFIX=\"\"" >> .config

.configure_win_crossbuild: &configure_win_crossbuild |
  # Append option
  ( \
    KV=$(grep "CT_CC_GCC_EXTRA_CONFIG_ARRAY" .config) \
    && echo "${KV%\"} --with-gnu-ld\"" >> .config; \
  )

# Actual build
.build_toolchain: &build_toolchain |
  ./ct-ng oldconfig
  ./ct-ng build

.add_extra_files: &add_extra_files |
  if [ "${EXTRA_BINS:-}" ]; then
    cp -v ${EXTRA_BINS} builds/${CONF_TARGET}/bin/
  fi

# Package the toolchain
.package_toolchain: &package_toolchain |
  mkdir -p dist
  cd builds
  rm -fv ${CONF_TARGET}/build.log*
  ${ARCHIVE_TOOL} ${ARCHIVE_NAME} ${CONF_TARGET}/ > tar-list.txt 2>&1
  mv tar-list.txt ..
  mv ${ARCHIVE_NAME} ../dist/
  echo "${ARCHIVE_NAME}" > ../dist/dist_name_${PLATFORM_NAME}_${CONF_TARGET}
  ls -l ../dist/
  cd -
  echo "Job disk usage $(du -hs ${CI_PROJECT_DIR})"

default_image:
  extends: .build_image_template
  stage: images
  variables:
    BUILD_IMAGE_URI: ${IMAGE_REGISTRY}-default:${IMAGE_TAG}
    BUILD_IMAGE_DOCKERFILE: ".gitlab/docker/default/Dockerfile"
  before_script: []

build-linux-x86_64_image:
  extends: .build_image_template
  stage: images
  variables:
    BUILD_IMAGE_URI: ${IMAGE_REGISTRY}-build-linux-x86_64:${IMAGE_TAG}
    BUILD_IMAGE_DOCKERFILE: ".gitlab/docker/build-linux-x86_64/Dockerfile"
  before_script: []

build-linux-i586_image:
  extends: .build_image_template
  stage: images
  variables:
    BUILD_IMAGE_URI: ${IMAGE_REGISTRY}-build-linux-i586:${IMAGE_TAG}
    BUILD_IMAGE_DOCKERFILE: ".gitlab/docker/build-linux-i586/Dockerfile"
  before_script: []

build-linux-arm-cross_image:
  extends: .build_image_template
  stage: images
  variables:
    BUILD_IMAGE_URI: ${IMAGE_REGISTRY}-build-linux-arm-cross:${IMAGE_TAG}
    BUILD_IMAGE_DOCKERFILE: ".gitlab/docker/build-linux-arm-cross/Dockerfile"
  before_script: []

generate_version:
  stage: generate_version
  tags: [ "build", "amd64" ]
  dependencies: []
  variables:
    GIT_SUBMODULE_STRATEGY: none
  artifacts:
    reports:
      dotenv: version.env
  script:
    - PREFIX="esp-linux-"
    - DIST_VERSION_SHORT=$(${CI_PROJECT_DIR}/maintainer/git-version-gen --prefix "${PREFIX}" .)
    - DIST_VERSION_FULL="${PREFIX}${DIST_VERSION_SHORT}"
    - true > version.env
    - echo "DIST_VERSION_FULL=$DIST_VERSION_FULL" >> version.env
    - echo "DIST_VERSION_SHORT=$DIST_VERSION_SHORT" >> version.env
    - cat version.env

# Common template for all builds
.build_template:
  stage: build
  allow_failure: true
  tags: [ "build", "amd64" ]
  dependencies: [ generate_version ]
  variables:
    # Do not compress artifacts because we already use compressed archives
    ARTIFACT_COMPRESSION_LEVEL: "fastest"
    ARCHIVE_NAME: ${CONF_TARGET}-${DIST_VERSION_SHORT}-${PLATFORM_NAME}.${ARCHIVE_EXT}
    CONF_BUILD: "x86_64-linux-gnu"
  artifacts:
    paths:
      - .config
      - build.log.bz2
      - tar-list.txt
      - dist
    when: always
    expire_in: 6 weeks
  after_script:
    # Use Git index to clean all except only needed files (to become artifacts)
    # Works on both failure and success
    - test -f .config && git add -f .config
    - test -f build.log && bzip2 build.log
    - test -f build.log.bz2 && git add -f build.log.bz2 && echo "You can view compressed build log with 'bzless'"
    - test -f tar-list.txt && git add -f tar-list.txt
    - test -d dist && git add -f dist
    - git clean -dxff >/dev/null
    - echo "Job disk usage $(du -hs ${CI_PROJECT_DIR})"

.build_template_linux:
  extends: .build_template
  script:
    - *build_ctng
    - *configure_common
    - *configure_docker
    - *configure_linux_no_pie
    - *build_toolchain
    - *package_toolchain

linux_x86_64_build:
  extends: .build_template_linux
  image: ${IMAGE_REGISTRY}-build-linux-x86_64:${IMAGE_TAG}
  variables:
    PLATFORM_NAME: "x86_64-linux-gnu"
    CONF_HOST: "x86_64-linux-gnu"

linux_i586_build:
  extends: .build_template_linux
  image: ${IMAGE_REGISTRY}-build-linux-i586:${IMAGE_TAG}
  variables:
    PLATFORM_NAME: "i586-linux-gnu"
    CONF_HOST: "i586-linux-gnu"

.template_lin_arm_cross:
  extends: .build_template
  image: ${IMAGE_REGISTRY}-build-linux-arm-cross:${IMAGE_TAG}
  script:
    - *build_ctng
    - *configure_common
    - *configure_docker
    - *configure_linux_no_pie
    - *configure_crossbuild
    - *build_toolchain
    - *package_toolchain

linux_aarch64_build:
  extends: .template_lin_arm_cross
  variables:
    PLATFORM_NAME: "aarch64-linux-gnu"
    CONF_HOST: "aarch64-linux-gnu"

linux_armhf_build:
  extends: .template_lin_arm_cross
  variables:
    PLATFORM_NAME: "arm-linux-gnueabihf"
    CONF_HOST: "arm-linux-gnueabihf"

linux_armel_build:
  extends: .template_lin_arm_cross
  variables:
    PLATFORM_NAME: "arm-linux-gnueabi"
    CONF_HOST: "arm-linux-gnueabi"

# Fix osxcross library paths in built binaries
.fix_macos_library_paths: &fix_macos_library_paths |
  pushd builds
  MACH_O_FILES=$(for file in $(find ${CONF_TARGET} -type f) ; do file $file; done | grep 'Mach-O' | awk '{print $1}' | sed 's/://g')
  for file in $MACH_O_FILES; do
    LIB_LIST=$(${CONF_HOST}-otool -L $file | awk '{print $1}' | grep osxcross || true);
    if [ "${LIB_LIST:-}" = "" ]; then
      continue;
    fi
    for lib in $LIB_LIST; do
      if [ $(basename $lib) != "libstdc++.6.dylib" ]; then
        echo "Unexpected library: $lib";
        exit 1;
      fi
      echo "Fixing library path $lib for file $file"
      ${CONF_HOST}-install_name_tool -change $lib "/usr/lib/$(basename $lib)" $file || ( echo "install_name_tool error... exiting" && exit 1 )
    done
  done
  popd

.template_macos_cross:
  extends: .build_template
  image: $CI_REGISTRY_IMAGE/build-macos:latest
  script:
    - *build_ctng
    - *configure_common
    - *configure_docker
    - *configure_crossbuild
    - *build_toolchain
    - *fix_macos_library_paths
    - *package_toolchain

# TODO: GCC-420. Disabled due to 'SDK/MacOSX15.5.sdk/usr/include/_stdio.h | :l318o:c7a:l  error: iexpected identifier'
.build_for_macos_x86_64:
  extends: .template_macos_cross
  variables:
    PLATFORM_NAME: "x86_64-apple-darwin"
    CONF_HOST: "x86_64-apple-darwin24.5"
    MACOSX_DEPLOYMENT_TARGET: "10.12"

# TODO: GCC-420. Disabled due to 'SDK/MacOSX15.5.sdk/usr/include/_stdio.h | :l318o:c7a:l  error: iexpected identifier'
.build_for_macos_arm64:
  extends: .template_macos_cross
  variables:
    PLATFORM_NAME: "aarch64-apple-darwin"
    CONF_HOST: "aarch64-apple-darwin24.5"
    MACOSX_DEPLOYMENT_TARGET: "10.13"

# TODO: GCC-434, add windows build

.needs_all_distros: &needs_all_distros
  dependencies:
    - generate_version
    - linux_x86_64_build
    - linux_i586_build
    - linux_aarch64_build
    - linux_armhf_build
    - linux_armel_build

.gen_sha256_file: &gen_sha256_file |
  FILES_LIST=$(find . -name dist_name_\* -exec cat {} \+)
  SHA256_FILE="${CI_PROJECT_NAME}-${DIST_VERSION_FULL}-checksum.sha256"
  for n in $FILES_LIST; do
    sz=$(stat -c%s "${n}")
    printf "# %s: %s bytes\n" "${n}" "${sz}" >> ${SHA256_FILE};
    sha256sum -b "${n}" >> ${SHA256_FILE};
  done
  FILES_LIST="${SHA256_FILE} ${FILES_LIST}"

upload_to_internal:
  stage: internal_deploy
  <<: *needs_all_distros
  when: manual
  allow_failure: true
  tags: [ "deploy", "shiny" ]
  variables:
    # don't use "GIT_STRATEGY: none", because we need cleaning old artifacts in 'dist/' that came from previous pipelines
    GIT_SUBMODULE_STRATEGY: none
    HTTP_UPLOAD_DIR: "${HTTP_UPLOAD_DIR}/riscv64/${DIST_VERSION_FULL}"
    HTTP_PUBLIC_DIR: "${HTTP_PUBLIC_DIR}/riscv64/${DIST_VERSION_FULL}"
  before_script:
    - *use_ci_tools
  script:
    - cd dist
    # Create a checksum file
    - *gen_sha256_file
    # Upload all needed files
    - cit_add_ssh_key "${HTTP_UPLOAD_KEY}"
    - ssh ${HTTP_UPLOAD_DIR%:*} "mkdir -p ${HTTP_UPLOAD_DIR#*:}"
    - scp ${FILES_LIST} ${HTTP_UPLOAD_DIR}
    # Show download links
    - echo -e "\nArchives were published there:\n\n$(for n in ${FILES_LIST}; do echo "${HTTP_PUBLIC_DIR}/${n}"; done)\n"
    - echo "${SHA256_FILE}:"
    - cat ${SHA256_FILE}

upload_to_dl_s3:
  stage: internal_deploy
  <<: *needs_all_distros
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  when: manual
  allow_failure: true
  tags: [ "deploy", "internet" ]
  variables:
    # don't use "GIT_STRATEGY: none", because we need cleaning old artifacts in 'dist/' that came from previous pipelines
    GIT_SUBMODULE_STRATEGY: none
    S3_UPLOAD_DIR: "s3://${DL_BUCKET}/dl/toolchains/preview/riscv64/${DIST_VERSION_SHORT}"
    S3_PUBLIC_DIR: "https://dl.espressif.com/dl/toolchains/preview/riscv64/${DIST_VERSION_SHORT}"
  before_script: []
  script:
    - cd dist
    # Create a checksum file
    - *gen_sha256_file

    # Upload all needed files
    - |
      for f in ${FILES_LIST}; do
        echo aws s3 cp --acl=public-read --no-progress "$f" "${S3_UPLOAD_DIR}/"
        aws s3 cp --acl=public-read --no-progress "$f" "${S3_UPLOAD_DIR}/"
      done

    # Show download links
    - |
      echo ""
      echo "Archives were published there:"
      for f in ${FILES_LIST}; do
        echo "${S3_PUBLIC_DIR}/${f}"
      done
      echo ""
    - echo "${SHA256_FILE}:"
    - cat ${SHA256_FILE}

# This image contains a prebuilt toolchain intended for testing other projects
linux_x86_64_docker:
  extends: .build_image_template
  stage: docker
  dependencies: [ generate_version, linux_x86_64_build ]
  when: manual
  allow_failure: true
  variables:
    PLATFORM_NAME: "x86_64-linux-gnu"
    BUILD_IMAGE: 1
    BUILD_IMAGE_URI: "${CI_REGISTRY_IMAGE}/dist-${CONF_TARGET}:${DIST_VERSION_SHORT}"
    BUILD_IMAGE_DOCKERFILE: ".gitlab/docker/dist/Dockerfile"
  before_script:
    - mv -v "dist/$(cat dist/dist_name_${PLATFORM_NAME}_${CONF_TARGET})" .gitlab/docker/dist/dist.tar.xz
