include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
  - macos_codesign

image: ${CI_DOCKER_REGISTRY}/esp32-ci-env

macos_codesign:
  stage: macos_codesign
  resource_group: macos_codesign
  tags: [ "darwin", "codesign" ]
  # list all jobs that produces macos distros
  variables:
    # URL to macos codesign repo
    NOTARIZATION_SCRIPTS_GIT: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HTTPS_SERVER}/espressif/macos_codesign_notarization.git"
  script:
    - echo $NOTARIZATION_SCRIPTS_GIT
    - git clone --depth=1 ${NOTARIZATION_SCRIPTS_GIT}

