FROM debian:bullseye

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    apt-utils \
    ca-certificates \
    git \
    curl wget \
    autoconf cmake make \
    texinfo \
    expect dejagnu \
    openssh-client iputils-ping \
    patch \
    python3 \
    timelimit \
    xz-utils zip unzip bzip2 lzip lzma \
  && rm -rf /var/lib/apt/lists/*
