ARG PYTHON_VERSION="3.10.13"
ARG OPENSSL_VERSION="3.3.1"
ARG LIBB2_VERSION="0.98.1"
ARG MESON_VERSION="1.5.1"
ARG NINJA_VERSION="1.11.1.1"

# install picolibc build dependencies
RUN apt-get remove -y python3 \
  && apt-get -y autoremove \
  && rm -rf /var/lib/apt/lists/* \
  && git clone https://github.com/BLAKE2/libb2.git --depth=1 -b v${LIBB2_VERSION} \
  && cd libb2 \
  && ./autogen.sh > /dev/null \
  && ./configure > /dev/null \
  && make -j$(nproc) > /dev/null \
  && make install > /dev/null \
  && cd .. \
  && rm -fr ./libb2 \
  && git clone https://github.com/python/cpython.git --depth=1 -b v$PYTHON_VERSION \
  && cd cpython \
  && ./configure LDFLAGS=-L/usr/lib > /dev/null \
  && make -j$(nproc) > /dev/null \
  && make install > /dev/null \
  && cd .. \
  && rm -fr ./cpython \
  && pip3 install --upgrade pip \
  && pip3 install meson==${MESON_VERSION} ninja==${NINJA_VERSION}
